#Configuration file for SDuels by skyerzz
#
#IF YOU CHANGE ANYTHING IN THIS FILE, USE /sduel reload INGAME!
#ONLY USE SPACES IN THIS FILE, NO TABS!

helpmessage:
  - "&7Help for Sduels"
  - "&cPut your help-message here."
  - "&cuse a - for each new line."

#textchat messages

#what a player sees if they get invited to duel
duelinvitemessage: "&e<player> Has challenged you to a duel. Click to accept!"

#if the duel gets cancelled, this message will be send to both players
duelcancelledmessage: "&cNo available arenas, Duel is cancelled!"

#if one of the players is already in game, this message in sent
alreadyingamemessage = "&eOne of the players is already in a duel!"

#The countdown for the battle. <seconds> gets replaced with the current seconds till the match begins.
countdownmessage: "&6The match begins in <seconds> seconds!"

#When the countdown ends, this messge is send to both players
startbattle: "&6GO!"

#This message is sent to the other player if an opponent picks a kit.
readymessage: "&6Your opponent is ready!"



#GUI texts
menuname: "&9Kit Menu"

potionname: "&6Potion PvP"
potionlore:
  - "&7POTION- Put your lore here"
  - "TEST"
  - "&cUse Empty lines for an empty space in the lore."
  
gapplename: "&6Gapple PvP"
gapplelore:
  - "&7GAPPLE- Put your lore here"
  - ""
  - "&cUse Empty lines for an empty space in the lore."
  
mcsgname: "&6MCSG"
mcsglore:
  - "&7MCSG- Put your lore here"
  - ""
  - "&cUse Empty lines for an empty space in the lore."


#arenas locations
arenas:
   #examples, remove the # to use this, and replace the locations with correct coordinates.
   #0:
   #  location1: x,y,z,yaw,pitch,worldname
   #  location2: x,y,z,yaw,pitch,worldname
   #1:
   #  location1: x,y,z,yaw,pitch,worldname
   #  location2: x,y,z,yaw,pitch,worldname