#Configuration file for SDuels by skyerzz
#
#IF YOU CHANGE ANYTHING IN THIS FILE, USE /sduel reload INGAME!
#ONLY USE SPACES IN THIS FILE, NO TABS!

helpmessage:
  - &7Help for Sduels
  - &cPut your help-message here.
  - &cuse a - for each new line.

arenas:
   #examples, remove the # to use this, and replace the locations with correct coordinates.
   #0:
   #  location1: x,y,z,yaw,pitch
   #  location2: x,y,z,yaw,pitch
   #1:
   #  location1: x,y,z,yaw,pitch
   #  location2: x,y,z,yaw,pitch